GitLabServer:
  image: 'gitlab/gitlab-ee:latest'
  restart: on-failure
  hostname: "${HOST_NAME}"
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://${HOST_NAME}'
  ports:
    - '80:80'
    - '22:22'
  volumes:
    - './config:/etc/gitlab'
